### ISSUE TITLE
Add instructions for building and running

### ISSUE THREAD

**Issue by tlewis11** [slfotg/chess-board#1]
Can you please provide some simple instructions for building and running this project in the Readme?

I've built the jar with `mvn package` and attempted to run with
`java -cp target/chess-board-0.0.1-SNAPSHOT.jar com.github.slfotg.chess.ChessBoard`

Error: Main method not found in class com.github.slfotg.chess.ChessBoard, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

**Comment by slfotg** [comment]
This is a library.  There is no main method and no way to run this.  You can only run tests.
